name: fruits_hup
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.3

#==================================  Dependencies  Section  ==============================
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # dependency to can make multi language for my app
  flutter_localizations:
    sdk: flutter

  # dependency to can make icon for my app
  flutter_launcher_icons: ^0.13.1
  # dependency to can use svg images
  flutter_svg: ^2.0.10+1
  # dependency for handle OnBoarding dots indicator
  dots_indicator: ^3.0.0
  # dependency for my local storage using shared preferences
  shared_preferences: ^2.3.2
  # dependency for my services
  get_it: ^8.0.0
  # dependency for either return type
  dartz: ^0.10.1
  # dependency for state managment
  flutter_bloc: ^8.1.6
  # dependency for loading indicator
  modal_progress_hud_nsn: ^0.5.0
  # dependency for comparison between two objects
  equatable: ^2.0.5

  # firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  email_validator: ^3.0.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.6
  flutter_svg_provider: ^1.0.7
  persistent_bottom_nav_bar: ^6.2.1
  skeletonizer: ^1.4.3
  provider: ^6.1.2
  flutter_paypal_payment: ^1.0.8
  url_launcher: ^6.2.5
  uuid: ^4.5.1

#==================================  Dev  Dependencies  Section  ==============================
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 24 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  flutter_lints: ^4.0.0

#==================================  Flutter  Section Add Images and Fonts ==============================
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

#==================================  Generate  Flutter  Assets  Section  ==============================
flutter_assets:
  assets_path: assets/icons/
  output_path: lib/core/utils/
  filename: assets1.dart
flutter_intl:
  enabled: true
